package guard

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

// The allowlists are checked against REAL parser output, not hand-written node
// lists.
//
// This exists because the first version of AllowedNodeKinds was written by
// hand and refused CASE WHEN, CAST, `||`, strftime and group_concat — most of
// what an ordinary analytical question needs. Nothing caught it: the other
// guard tests hand-write their NodeKinds, so they only ever asserted against
// the same guesses the allowlist was built from.
//
// A guard that refuses legitimate SQL does not look like a guard bug. It looks
// like the model writing bad SQL, and it shows up as a collapsed execution
// accuracy at P2 — a long way from the cause.
//
// The corpus is generated by apps/retriever-python (see the header in the
// fixture file) and committed, so this suite needs no Python at run time and CI
// needs no cross-service orchestration. Regenerate it when sqlglot moves.

type corpusCase struct {
	SQL       string   `json:"sql"`
	NodeKinds []string `json:"node_kinds"`
	Functions []string `json:"functions"`
}

type corpus struct {
	SqlglotVersion string       `json:"sqlglot_version"`
	Legitimate     []corpusCase `json:"legitimate"`
	Adversarial    []corpusCase `json:"adversarial"`
}

func loadCorpus(t *testing.T) corpus {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot locate the test file")
	}
	path := filepath.Join(filepath.Dir(thisFile), "testdata", "sqlglot_corpus.json")

	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading the parser corpus: %v", err)
	}
	var c corpus
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatalf("decoding the parser corpus: %v", err)
	}
	if len(c.Legitimate) == 0 || len(c.Adversarial) == 0 {
		t.Fatal("the parser corpus is empty on one side")
	}
	return c
}

func TestAllowlistsAdmitEveryLegitimateStatement(t *testing.T) {
	for _, tc := range loadCorpus(t).Legitimate {
		t.Run(tc.SQL, func(t *testing.T) {
			for _, kind := range tc.NodeKinds {
				if !AllowedNodeKinds[kind] {
					t.Errorf("AllowedNodeKinds refuses %q, so this statement could "+
						"never execute:\n  %s\n"+
						"An ordinary question would be refused and it would look like "+
						"the model wrote bad SQL.", kind, tc.SQL)
				}
			}
			for _, fn := range tc.Functions {
				if !AllowedFunctions[fn] {
					t.Errorf("AllowedFunctions refuses %q, so this statement could "+
						"never execute:\n  %s", fn, tc.SQL)
				}
			}
		})
	}
}

func TestAllowlistsRefuseEveryAdversarialStatement(t *testing.T) {
	for _, tc := range loadCorpus(t).Adversarial {
		t.Run(tc.SQL, func(t *testing.T) {
			// Refused on at least one axis. Which axis matters: a DROP is
			// caught on its node kind, while readfile is caught only on its
			// NAME — it shares the Anonymous kind with printf and julianday,
			// which is the whole reason parse_summary.v1 carries `functions`.
			var refusedKind, refusedFunc string
			for _, kind := range tc.NodeKinds {
				if !AllowedNodeKinds[kind] {
					refusedKind = kind
					break
				}
			}
			for _, fn := range tc.Functions {
				if !AllowedFunctions[fn] {
					refusedFunc = fn
					break
				}
			}
			if refusedKind == "" && refusedFunc == "" {
				t.Fatalf("BOTH allowlists admit every part of:\n  %s\n"+
					"kinds=%v functions=%v\n"+
					"This statement would execute.", tc.SQL, tc.NodeKinds, tc.Functions)
			}
		})
	}
}

func TestTheFunctionAllowlistIsWhatCatchesFileFunctions(t *testing.T) {
	// The design claim, asserted rather than assumed. If someone "hardens" the
	// guard by removing Anonymous from AllowedNodeKinds, ordinary SQL breaks;
	// if someone drops the function allowlist as redundant, file functions get
	// through. Both mistakes are caught here.
	if !AllowedNodeKinds["Anonymous"] {
		t.Error("Anonymous is not allowlisted as a node kind — printf and julianday " +
			"arrive as that kind and would be refused along with readfile")
	}
	for _, fn := range []string{
		"readfile", "writefile", "load_extension",
		"pg_read_file", "pg_ls_dir", "lo_import", "lo_export", "system",
	} {
		if AllowedFunctions[fn] {
			t.Errorf("AllowedFunctions permits %q; with Anonymous allowlisted as a "+
				"kind, this list is the ONLY thing refusing it", fn)
		}
	}
	// And the harmless ones that share the Anonymous kind must still pass.
	for _, fn := range []string{"printf", "julianday"} {
		if !AllowedFunctions[fn] {
			t.Errorf("AllowedFunctions refuses %q, which is an ordinary function "+
				"that happens to share a node kind with readfile", fn)
		}
	}
}
